version: "3.8"

networks:
  house_finder_web:

services:
          
  webapp_house_finder:
    container_name: flask_house_finder
    build:
      context: ./webapp-house-finder
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5003:5003"
    volumes:
      - ./images/api:/app/app/static/images/img-projects
      - ./images/profile:/app/app/static/images/img-profile
      - ./logs/web-logs/log.log:/app/app/logs_system/log.log
    environment:
      - DB_URL=${DB_URL}
      - SECRET_APP_KEY=${SECRET_APP_KEY}
      - FLASK_APP=${FLASK_APP}
      - CONFIGURATION_SETUP=${CONFIGURATION_SETUP}
      - APP_PASSWORD_EMAIL=${APP_PASSWORD_EMAIL}
      - ADMINISTER_EMAIL=${ADMINISTER_EMAIL}
      - DEBUG=False
      - SERVER_NAME=${SERVER_NAME}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - mysql_db
    env_file:
      - .env
    networks:
      - house_finder_web
  
  api_house_finder:
    container_name: fastapi_house_finder
    build:
      context: ./api-house-finder
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./images/api:/app/app/static/images/img-projects
      - ./logs/api-logs/log.log:/app/app/logs_system/log.log
    environment:
      - DB_URL=${DB_URL}
      - SECRET_APP_KEY=${SECRET_APP_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - mysql_db
    env_file:
      - .env
    networks:
      - house_finder_web

  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl/cert.pem:/etc/nginx/ssl/cert.pem
      - ./nginx/ssl/key.pem:/etc/nginx/ssl/key.pem   
    depends_on:
      - webapp_house_finder
      - api_house_finder
    environment:
      - SERVER_NAME=${SERVER_NAME}
    networks:
      - house_finder_web


  mysql_db:
    container_name: mysql_db
    image: mysql:latest
    restart: always
    volumes:
      - ./mysql_db/mysql_data:/var/lib/mysql
      - ./mysql_db/scripts_sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env
    networks:
      - house_finder_web


volumes:
  mysql_data:
  images: