"""empty message

Revision ID: 8438df1f5f1c
Revises: 95c2a56f3a39
Create Date: 2024-05-12 17:47:53.373424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8438df1f5f1c'
down_revision = '95c2a56f3a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('area',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=False)
        batch_op.alter_column('area',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###
